### ISSUE TITLE
Tool not configured yet

### ISSUE THREAD

**Issue by kidexx** [roots84/DNS-Swapper#7]
Hi, I installed it on a Windows 10 PC with one admin account and one regular account. Logging in to the regular account / windows profile I get now everytime the message "Tool not configured yet" - no matter if I configured it in between. After rebooting, again the message "Tool not configured yet". 
How can I solve the issue?
Cheers

**Comment by tryallthethings** [comment]
Hey!
It should work regardless of admin or regular user account as the config is written to the user's appdata folder such as `C:\Users\username\AppData\Local\DNS_Swapper\DNS-Swapper.exe_Url_2vkzryni5blagkgybxtiai1dd3qne5zd\1.5.3.0\user.config`. The configuration is saved when you exit the tool or do it manually via File -> Save. It probably didn't save if you just configured it and rebooted afterward.
I should probably add automatic saving if a field is changed.

Could you please try manually saving or exiting the application and let me know if that works? 
Please note that changing the DNS settings requires elevated permissions, so an Admin would need to enter his / her credentials every time the user wants to change the DNS.

**Comment by kidexx** [comment]
Hi, thanks. I feel like an idiot, just pressing the save button seem to solve the issue. Before I did not save it explicit because I thought it will store it automatically.

Anyhow, great tool! 
Thank you for your support!

I am by the way searching something similar for Linux ... if somebody here does have a tip ... would be appreciated ;-)

**Comment by tryallthethings** [comment]
No worries. It's not obvious and there is no automatic saving at the moment. I'm going to add that and release a new version soon.
Thank you for the praise! As I'm only using Linux on my servers (without GUI) I'm not aware of a Linux alternative for this tool. But you could probably achieve the same without a GUI with 2 bash scripts (or one that accepts command line arguments).
